### ISSUE TITLE
Cannot connect to server on watchOS 9 beta

### ISSUE THREAD

**Issue by Rexios80** [pusher/NWWebSocket#35]
This is most definitely a watchOS issue, but I wanted to make it known and see if anyone here might have some insight into this. The exact same code using NWWebSocket works on watchOS 8, but on watchOS 9 I get:

```console
Socket error: POSIXErrorCode(rawValue: 50): Network is down
Socket error: POSIXErrorCode(rawValue: 50): Network is down
```

I'm going to create a minimal reproducible example using the raw NWConnection library to see if I can learn anything, but considering how vague this error is I doubt I'll get very far. [URLSessionWebSocketTask](https://developer.apple.com/documentation/foundation/urlsessionwebsockettask) also broke in watchOS 9. Knowing that websockets are handled by the phone, I'm guessing that the phone part of watch websockets got broken.

**Comment by benjamin-tang-pusher** [comment]
Can this be reproduced in XCode's watch simulator?

**Comment by Rexios80** [comment]
Unfortunately no

**Comment by benjamin-tang-pusher** [comment]
I don't have a physical Apple watch at hand to reproduce this, I will try to get one and see if I can reproduce it.

**Comment by benjamin-tang-pusher** [comment]
Could you make a minimal reproduction repo with a watch project? I haven't made one before, and when I add the NWWebsocket package to a watch project, I can't import it into my ContentView. I think it's because it's in an extension. I've used pure NWWebsocket in another iOS project before.

**Comment by Rexios80** [comment]
https://github.com/Rexios80/watchos_nwwebsocket_test

**Comment by Rexios80** [comment]
Sorry it took so long. I've been busy with a bunch of other things.

**Comment by paulb777** [comment]
Also see https://developer.apple.com/forums/thread/714796 for a minimal repro of the watchOS 9 issue.

**Comment by Rexios80** [comment]
Also see that linked issue from the Firebase iOS repo. We might just be screwed 🙃

**Comment by Rexios80** [comment]
Welp I guess sockets on watchOS are dead

**Comment by benjamin-tang-pusher** [comment]
Yep, the evidence points to watchOS 9 strictly blocking low level networking.

It also mentions that the simulator doesn't enforce this, which explains why I couldn't reproduce this on the sim.

**Comment by Rexios80** [comment]
How do you want to handle this? Just remove watchOS support from the podspec and package manifest?

**Comment by benjamin-tang-pusher** [comment]
That, and I will modify the readme.

**Comment by benjamin-tang-pusher** [comment]
I've removed mention of watchOS from the Readme. I'm going to leave it in the other files in the off chance someone is using it in older versions of watchOS.
