### ISSUE TITLE
Need help to fix iOS version issue | 'NWProtocolWebSocket' is only available in iOS 13.0 or newer

### ISSUE THREAD

**Issue by kmrAX** [pusher/NWWebSocket#37]
Hi,
I have added `NWWebSocket` using pod.

`pod 'NWWebSocket', '~> 0.5.2'`

After adding and updating the pod, Xcode is giving me this error

`'NWProtocolWebSocket' is only available in iOS 13.0 or newer`

![image](https://user-images.githubusercontent.com/83965285/202830898-e6203896-096e-4173-89aa-e1a4c4850fab.png)

But, my target iOS is 15.

![image](https://user-images.githubusercontent.com/83965285/202830914-fe984d86-0f1d-46c5-8186-964769203858.png)

Can you please let me know if I am missing something here?

**Comment by benjamin-tang-pusher** [comment]
I'm going to close this issue, feel free to reopen if the above setting isn't the right one.

**Comment by QuentinDela** [comment]
Hello, 
I am having this issue also.
I did change the iOS Deployment Target to 13.0 but I still get the error " 'NWConnection' is only available in iOS 12.0 or newer"
